<?php

namespace Tests\Feature;

use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class UserTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $auth = User::where('email', 'root@mail.com')->first();
        $this->actingAs($auth);
    }

    /**
     * A basic feature test example.
     */
    public function test_user_view_success()
    {
        $response = $this->get(url('/admin/user'));
        return $response->assertStatus(200);
    }

    /**
     * A basic feature test example.
     * @depends test_user_view_success
     * @group user
     */
    public function test_user_view_not_found()
    {
        $response = $this->get(url('/admin/userw1'));
        return $response->assertStatus(404);
    }
}
